var classes = [
    {
        "name": "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\Auth\\LoginRequest",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 1,
        "effort": 33.6,
        "level": 1,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 33.6,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 9,
        "loc": 30,
        "lloc": 21,
        "mi": 97.85,
        "mIwoC": 60.34,
        "commentWeight": 37.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.41,
        "relativeSystemComplexity": 64.41,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 1.22,
        "totalSystemComplexity": 193.22,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ConfirmablePasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Validation\\ValidationException"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 10,
        "volume": 49.83,
        "difficulty": 1.5,
        "effort": 74.74,
        "level": 0.67,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 33.22,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 6,
        "loc": 22,
        "lloc": 16,
        "mi": 97.76,
        "mIwoC": 61.58,
        "commentWeight": 36.18,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.31,
        "relativeSystemComplexity": 49.31,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 98.63,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 1.5,
        "effort": 34.9,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 15.51,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 15,
        "lloc": 12,
        "mi": 98.56,
        "mIwoC": 66.62,
        "commentWeight": 31.94,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 25.5,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\EmailVerificationPromptController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.67,
        "effort": 6.67,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 109.21,
        "mIwoC": 73.03,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\NewPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Str",
            "Illuminate\\Auth\\Events\\PasswordReset",
            "Illuminate\\Support\\Facades\\Password"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 40,
        "vocabulary": 16,
        "volume": 160,
        "difficulty": 4.15,
        "effort": 664.62,
        "level": 0.24,
        "bugs": 0.05,
        "time": 37,
        "intelligentContent": 38.52,
        "number_operators": 4,
        "number_operands": 36,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 14,
        "loc": 31,
        "lloc": 17,
        "mi": 100.6,
        "mIwoC": 57.46,
        "commentWeight": 43.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 144.23,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0.46,
        "totalSystemComplexity": 288.46,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 11,
        "volume": 62.27,
        "difficulty": 1.78,
        "effort": 110.7,
        "level": 0.56,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 35.03,
        "number_operators": 2,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 99.36,
        "mIwoC": 65.49,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 36.29,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordResetLinkController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Password"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 8,
        "volume": 60,
        "difficulty": 4.8,
        "effort": 288,
        "level": 0.21,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 12.5,
        "number_operators": 4,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 25,
        "lloc": 14,
        "mi": 105.08,
        "mIwoC": 62.28,
        "commentWeight": 42.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 36.36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 72.71,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\RegisteredUserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "Illuminate\\Auth\\Events\\Registered",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 31,
        "vocabulary": 16,
        "volume": 124,
        "difficulty": 3.12,
        "effort": 386.31,
        "level": 0.32,
        "bugs": 0.04,
        "time": 21,
        "intelligentContent": 39.8,
        "number_operators": 4,
        "number_operands": 27,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 8,
        "loc": 24,
        "lloc": 16,
        "mi": 97.93,
        "mIwoC": 58.94,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\VerifyEmailController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Foundation\\Auth\\EmailVerificationRequest",
            "Illuminate\\Auth\\Events\\Verified"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 4,
        "effort": 144.76,
        "level": 0.25,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 9.05,
        "number_operators": 6,
        "number_operands": 8,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 17,
        "lloc": 14,
        "mi": 93.97,
        "mIwoC": 63.68,
        "commentWeight": 30.29,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 16.6,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\CitaController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cancelar",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "confirmar",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "horariosDisponibles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filtrarDoctores",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verificarConflictoHorario",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "enviarEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "construirEmailHTML",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 14,
        "nbMethods": 14,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 55,
        "ccn": 42,
        "ccnMethodMax": 14,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Cita",
            "App\\Models\\Doctor",
            "App\\Models\\Paciente",
            "App\\Models\\TipoCita",
            "App\\Models\\Paciente",
            "App\\Models\\Doctor",
            "App\\Models\\TipoCita",
            "Illuminate\\Http\\Request",
            "App\\Models\\Costo",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Cita",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Cita",
            "App\\Models\\Cita",
            "App\\Models\\Paciente",
            "App\\Models\\Doctor",
            "App\\Models\\TipoCita",
            "Illuminate\\Http\\Request",
            "App\\Models\\Cita",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Cita",
            "App\\Models\\Cita",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Cita",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Http\\Request",
            "App\\Models\\Doctor",
            "Carbon\\Carbon",
            "App\\Models\\Cita",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Illuminate\\Http\\Request",
            "App\\Models\\Doctor",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Cita",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Cita",
            "Carbon\\Carbon",
            "Illuminate\\Support\\Facades\\Mail",
            "Illuminate\\Support\\Facades\\Log",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 11,
        "length": 869,
        "vocabulary": 205,
        "volume": 6673.47,
        "difficulty": 17.54,
        "effort": 117042.37,
        "level": 0.06,
        "bugs": 2.22,
        "time": 6502,
        "intelligentContent": 380.5,
        "number_operators": 185,
        "number_operands": 684,
        "number_operators_unique": 10,
        "number_operands_unique": 195,
        "cloc": 85,
        "loc": 391,
        "lloc": 302,
        "mi": 46.53,
        "mIwoC": 13.47,
        "commentWeight": 33.06,
        "kanDefect": 2.79,
        "relativeStructuralComplexity": 7744,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 7744.28,
        "totalStructuralComplexity": 108416,
        "totalDataComplexity": 3.99,
        "totalSystemComplexity": 108419.99,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 12,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.19,
        "afferentCoupling": 14,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\EmpleadoController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "indexDoctores",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "indexStaff",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 24,
        "ccn": 18,
        "ccnMethodMax": 10,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Empleado",
            "App\\Models\\Cargo",
            "App\\Models\\Especialidad",
            "Illuminate\\Http\\Request",
            "App\\Models\\Empleado",
            "App\\Models\\Cargo",
            "App\\Models\\Especialidad",
            "Illuminate\\Http\\Request",
            "App\\Models\\Empleado",
            "App\\Models\\Cargo",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Empleado",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Doctor",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Horario",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Empleado",
            "App\\Models\\Cargo",
            "App\\Models\\Especialidad",
            "App\\Models\\Horario",
            "Illuminate\\Http\\Request",
            "App\\Models\\Empleado",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Horario",
            "App\\Models\\Horario",
            "Illuminate\\Support\\Str",
            "App\\Models\\Horario",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Empleado"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 473,
        "vocabulary": 133,
        "volume": 3337.15,
        "difficulty": 11.31,
        "effort": 37728.32,
        "level": 0.09,
        "bugs": 1.11,
        "time": 2096,
        "intelligentContent": 295.18,
        "number_operators": 66,
        "number_operands": 407,
        "number_operators_unique": 7,
        "number_operands_unique": 126,
        "cloc": 30,
        "loc": 199,
        "lloc": 169,
        "mi": 52.6,
        "mIwoC": 24.31,
        "commentWeight": 28.29,
        "kanDefect": 1.7,
        "relativeStructuralComplexity": 1681,
        "relativeDataComplexity": 0.24,
        "relativeSystemComplexity": 1681.24,
        "totalStructuralComplexity": 11767,
        "totalDataComplexity": 1.69,
        "totalSystemComplexity": 11768.69,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PacienteController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "activate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Paciente",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Str",
            "App\\Models\\Paciente",
            "App\\Models\\Paciente",
            "Illuminate\\Http\\Request",
            "App\\Models\\Paciente",
            "App\\Models\\Paciente",
            "App\\Models\\Paciente"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 295,
        "vocabulary": 105,
        "volume": 1980.7,
        "difficulty": 5.43,
        "effort": 10746.78,
        "level": 0.18,
        "bugs": 0.66,
        "time": 597,
        "intelligentContent": 365.06,
        "number_operators": 21,
        "number_operands": 274,
        "number_operators_unique": 4,
        "number_operands_unique": 101,
        "cloc": 27,
        "loc": 150,
        "lloc": 123,
        "mi": 61.61,
        "mIwoC": 31.06,
        "commentWeight": 30.55,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 225.5,
        "totalStructuralComplexity": 1575,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 1578.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PagoController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pagosPorEstado",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pagosPorFecha",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pago",
            "App\\Models\\Cita",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pago",
            "App\\Models\\DetallePago",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pago",
            "App\\Models\\Cita",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pago",
            "App\\Models\\Pago",
            "App\\Models\\Pago",
            "App\\Models\\Pago",
            "App\\Models\\Pago"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 9,
        "length": 163,
        "vocabulary": 56,
        "volume": 946.6,
        "difficulty": 9.36,
        "effort": 8857.46,
        "level": 0.11,
        "bugs": 0.32,
        "time": 492,
        "intelligentContent": 101.16,
        "number_operators": 32,
        "number_operands": 131,
        "number_operators_unique": 7,
        "number_operands_unique": 49,
        "cloc": 10,
        "loc": 87,
        "lloc": 77,
        "mi": 62.27,
        "mIwoC": 37.2,
        "commentWeight": 25.07,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 900,
        "relativeDataComplexity": 0.35,
        "relativeSystemComplexity": 900.35,
        "totalStructuralComplexity": 8100,
        "totalDataComplexity": 3.19,
        "totalSystemComplexity": 8103.19,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\ProfileUpdateRequest",
            "Illuminate\\Support\\Facades\\Redirect",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Redirect"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 32,
        "vocabulary": 14,
        "volume": 121.84,
        "difficulty": 3.55,
        "effort": 431.96,
        "level": 0.28,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 34.36,
        "number_operators": 6,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 36,
        "lloc": 27,
        "mi": 88.87,
        "mIwoC": 53.9,
        "commentWeight": 34.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 196.27,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 588.8,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Auth\\LoginRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "authenticate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ensureIsNotRateLimited",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "throttleKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Validation\\ValidationException",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Auth\\Events\\Lockout",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Validation\\ValidationException",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Str"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 3,
        "length": 43,
        "vocabulary": 18,
        "volume": 179.31,
        "difficulty": 6.35,
        "effort": 1137.91,
        "level": 0.16,
        "bugs": 0.06,
        "time": 63,
        "intelligentContent": 28.25,
        "number_operators": 10,
        "number_operands": 33,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 21,
        "loc": 55,
        "lloc": 34,
        "mi": 91.29,
        "mIwoC": 50.41,
        "commentWeight": 40.88,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 196.27,
        "totalStructuralComplexity": 980,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 981.33,
        "package": "App\\Http\\Requests\\Auth\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\ProfileUpdateRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 8,
        "volume": 36,
        "difficulty": 0.79,
        "effort": 28.29,
        "level": 1.27,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 45.82,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 110.25,
        "mIwoC": 69.27,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Mail\\ExampleEmail",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "envelope",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "content",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attachments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Mail\\Mailable",
            "Illuminate\\Mail\\Mailables\\Envelope",
            "Illuminate\\Mail\\Mailables\\Envelope",
            "Illuminate\\Mail\\Mailables\\Content",
            "Illuminate\\Mail\\Mailables\\Content"
        ],
        "parents": [
            "Illuminate\\Mail\\Mailable"
        ],
        "implements": [],
        "lcom": 4,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 0.5,
        "effort": 3.96,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15.85,
        "number_operators": 3,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 15,
        "loc": 35,
        "lloc": 20,
        "mi": 107.64,
        "mIwoC": 65.19,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 12,
        "totalSystemComplexity": 12,
        "package": "App\\Mail\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Cargo",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "empleados",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 7,
        "volume": 25.27,
        "difficulty": 0.67,
        "effort": 16.84,
        "level": 1.5,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 37.9,
        "number_operators": 1,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 65.74,
        "mIwoC": 65.74,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Cita",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "paciente",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "doctor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tipoCita",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pagos",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNombrePacienteAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNombreDoctorAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scopeEstado",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scopeFecha",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scopeHoy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scopeFuturas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model",
            "Illuminate\\Support\\Str",
            "static"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 8,
        "length": 86,
        "vocabulary": 37,
        "volume": 448.01,
        "difficulty": 5.31,
        "effort": 2380.07,
        "level": 0.19,
        "bugs": 0.15,
        "time": 132,
        "intelligentContent": 84.33,
        "number_operators": 18,
        "number_operands": 68,
        "number_operators_unique": 5,
        "number_operands_unique": 32,
        "cloc": 20,
        "loc": 100,
        "lloc": 80,
        "mi": 71.18,
        "mIwoC": 39.25,
        "commentWeight": 31.94,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 65.17,
        "totalStructuralComplexity": 704,
        "totalDataComplexity": 12.89,
        "totalSystemComplexity": 716.89,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Models\\Costo",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "tipoCita",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 11,
        "volume": 41.51,
        "difficulty": 0.55,
        "effort": 22.83,
        "level": 1.82,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 75.48,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 3,
        "loc": 16,
        "lloc": 13,
        "mi": 95.32,
        "mIwoC": 64.24,
        "commentWeight": 31.08,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\DetallePago",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "pago",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 11,
        "volume": 41.51,
        "difficulty": 0.55,
        "effort": 22.83,
        "level": 1.82,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 75.48,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 2,
        "loc": 15,
        "lloc": 13,
        "mi": 91.04,
        "mIwoC": 64.24,
        "commentWeight": 26.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Doctor",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "empleado",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "especialidad",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "horarios",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "citas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 3,
        "length": 29,
        "vocabulary": 18,
        "volume": 120.93,
        "difficulty": 0.74,
        "effort": 88.92,
        "level": 1.36,
        "bugs": 0.04,
        "time": 5,
        "intelligentContent": 164.46,
        "number_operators": 4,
        "number_operands": 25,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 19,
        "loc": 60,
        "lloc": 41,
        "mi": 88.38,
        "mIwoC": 50.1,
        "commentWeight": 38.27,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 40,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Empleado",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cargo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "doctor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 30,
        "vocabulary": 20,
        "volume": 129.66,
        "difficulty": 0.71,
        "effort": 92.13,
        "level": 1.41,
        "bugs": 0.04,
        "time": 5,
        "intelligentContent": 182.48,
        "number_operators": 3,
        "number_operands": 27,
        "number_operators_unique": 1,
        "number_operands_unique": 19,
        "cloc": 5,
        "loc": 42,
        "lloc": 37,
        "mi": 76.33,
        "mIwoC": 50.86,
        "commentWeight": 25.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Horario",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "doctores",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 13,
        "volume": 66.61,
        "difficulty": 0.71,
        "effort": 47.18,
        "level": 1.41,
        "bugs": 0.02,
        "time": 3,
        "intelligentContent": 94.03,
        "number_operators": 1,
        "number_operands": 17,
        "number_operators_unique": 1,
        "number_operands_unique": 12,
        "cloc": 5,
        "loc": 32,
        "lloc": 27,
        "mi": 84.61,
        "mIwoC": 55.87,
        "commentWeight": 28.74,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Paciente",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "citas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 17,
        "volume": 85.84,
        "difficulty": 0.63,
        "effort": 53.65,
        "level": 1.6,
        "bugs": 0.03,
        "time": 3,
        "intelligentContent": 137.34,
        "number_operators": 1,
        "number_operands": 20,
        "number_operators_unique": 1,
        "number_operands_unique": 16,
        "cloc": 7,
        "loc": 21,
        "lloc": 14,
        "mi": 100.32,
        "mIwoC": 61.32,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.07,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Pago",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "cita",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "detalles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 17,
        "vocabulary": 13,
        "volume": 62.91,
        "difficulty": 0.63,
        "effort": 39.32,
        "level": 1.6,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 100.65,
        "number_operators": 2,
        "number_operands": 15,
        "number_operators_unique": 1,
        "number_operands_unique": 12,
        "cloc": 2,
        "loc": 19,
        "lloc": 17,
        "mi": 84.52,
        "mIwoC": 60.43,
        "commentWeight": 24.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "App\\Models\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\TipoCita",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "costos",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "citas",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 10,
        "volume": 53.15,
        "difficulty": 0.78,
        "effort": 41.34,
        "level": 1.29,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 68.34,
        "number_operators": 2,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 4,
        "loc": 23,
        "lloc": 19,
        "mi": 89.99,
        "mIwoC": 59.89,
        "commentWeight": 30.1,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "casts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "implements": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 8,
        "volume": 30,
        "difficulty": 0.64,
        "effort": 19.29,
        "level": 1.56,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 46.67,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 16,
        "loc": 28,
        "lloc": 12,
        "mi": 112.04,
        "mIwoC": 65.98,
        "commentWeight": 46.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 8,
        "loc": 18,
        "lloc": 10,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\View\\Components\\AppLayout",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\View\\Component",
            "Illuminate\\View\\View"
        ],
        "parents": [
            "Illuminate\\View\\Component"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 114.24,
        "mIwoC": 78.06,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\View\\Components\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\View\\Components\\GuestLayout",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\View\\Component",
            "Illuminate\\View\\View"
        ],
        "parents": [
            "Illuminate\\View\\Component"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 114.24,
        "mIwoC": 78.06,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\View\\Components\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]